openapi: 3.0.0
info:
  title: Contacts
  description: A contact is either a customer or vendor. A contact can be an individual or a business in general.
  contact: {}
  version: 1.0.0
servers:
  - url: https://www.zohoapis.com/inventory/v1
    description: API Endpoint
tags:
  - name: contacts
    description: Contacts Module
paths:
  /contacts:
    x-mcp-group:
      - Contacts
    post:
      tags:
        - contacts
      operationId: create_contact
      summary: Create a Contact
      description: Create a contact with given information.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.CREATE
    get:
      tags:
        - contacts
      operationId: list_contacts
      summary: List contacts
      description: List all contacts with pagination.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.READ
  /contacts/{contact_id}:
    x-mcp-group:
      - Contacts
    put:
      tags:
        - contacts
      operationId: update_contact
      summary: Update a contact
      description: Update an existing contact. To delete a contact person remove it from the contact_persons list.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.UPDATE
    get:
      tags:
        - contacts
      operationId: get_contact
      summary: Get contact
      description: Get details of a contact.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.READ
    delete:
      tags:
        - contacts
      operationId: delete_contact
      summary: Delete a contact
      description: Delete an existing contact.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.DELETE
  /contacts/{contact_id}/address:
    x-mcp-group:
      - Contacts
    get:
      tags:
        - contacts
      operationId: get_contact_address
      summary: Get contact address
      description: Get the billing and shipping address of an existing contact
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.READ
  /contacts/{contact_id}/active:
    x-mcp-group:
      - Contacts
    post:
      tags:
        - contacts
      operationId: mark_contact_as_active
      summary: Mark as active
      description: Mark a contact as active.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.CREATE
  /contacts/{contact_id}/inactive:
    x-mcp-group:
      - Contacts
    post:
      tags:
        - contacts
      operationId: mark_contact_as_inactive
      summary: Mark as Inactive
      description: Mark a contact as inactive.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.CREATE
  /contacts/{contact_id}/statements/email:
    x-mcp-group:
      - Contacts
    post:
      tags:
        - contacts
      operationId: email_statement
      summary: Email statement
      description: Email statement to the contact. If JSONString is not inputted, mail will be sent with the default mail content.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.CREATE
    get:
      tags:
        - contacts
      operationId: get_statement_mail_content
      summary: Get Statement mail content
      description: Get the mail content of a contacts billing statement.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.READ
  /contacts/{contact_id}/email:
    x-mcp-group:
      - Contacts
    post:
      tags:
        - contacts
      operationId: email_contact
      summary: Email contact
      description: Send email to contact.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.CREATE
  /contacts/{contact_id}/comments:
    x-mcp-group:
      - Contacts
    get:
      tags:
        - contacts
      operationId: list_contact_comments
      summary: List Comments
      description: List recent activities of a contact.
      deprecated: false
      security:
        - Zoho_Auth:
            - ZohoInventory.contacts.READ
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.zoho.com/oauth/v2/auth
          scopes:
            ZohoInventory.contacts.CREATE: Create Contacts
            ZohoInventory.contacts.UPDATE: Update Contacts
            ZohoInventory.contacts.READ: Read Contacts
            ZohoInventory.contacts.DELETE: Delete Contacts
