name: Setup CI
description: 'Setup Bun for CI'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.3.2'
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile