name: Publish
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    uses: ./.github/workflows/ci.yml

  release:
    name: Publish
    needs: [check]
    if: github.repository == 'matagaralph/zapi-inventory'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - run: vp install
      - run: vp pack
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          version: vp run changeset:version
          publish: vp run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
